#!/usr/bin/env bash
#Configures a linux server as follows;
#localhost resolves to 127.0.0.2 and
#facebook.com resolves to 8.8.8.8, after running

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /stc/hosts
